service: skillet-backend

package:
  individually: true

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  lambdaHashingVersion: 20201221

  environment:
    spoonacularAPIKey: ${env:SPOONACULAR_API_KEY}

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  hello:
    handler: handler.main
    events:
      - http:
          path: hello
          method: get

  search:
    handler: search.main
    events:
      - http:
          path: search
          method: post

  getinfo:
    handler: getinfo.main
    events:
      - http:
          path: info/{id}
          method: get


