service: skillet-backend

package:
  individually: true

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  lambdaHashingVersion: 20201221

  environment:
    spoonacularAPIKey: ${env:SPOONACULAR_API_KEY}

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

functions:

  search:
    handler: search.main
    events:
      - http:
          path: recipes/search
          method: post
          cors: true

  getinfo:
    handler: getinfo.main
    events:
      - http:
          path: recipes/info/{id}
          method: get
          cors: true

  getsteps:
    handler: getsteps.main
    events:
      - http:
          path: recipes/steps/{id}
          method: get
          cors: true

  getsimilar:
    handler: getsimilar.main
    events:
      - http:
          path: recipes/similar/{id}
          method: get
          cors: true


